"""
Static ARK Trivia Questions - Curated and verified for accuracy.
Aim for ~200 questions covering creatures, taming, breeding, maps, mechanics, lore.
"""

ARK_TRIVIA_QUESTIONS = [
    # ============ CREATURE FACTS ============
    {"q": "What is the scientific name of the T-Rex in ARK?", "options": ["Tyrannosaurus", "Tyrannosaurus Rex", "T-Rex", "Rex"], "answer": 1},
    {"q": "How long does it take for a Rex egg to hatch (without boost)?", "options": ["2 hours", "4 hours", "7 hours", "1 day"], "answer": 2},
    {"q": "What is the base health of a wild T-Rex?", "options": ["1100", "2200", "3650", "5500"], "answer": 2},
    {"q": "Which creature can harvest the most meat per swing?", "options": ["T-Rex", "Allosaurus", "Spino", "Carno"], "answer": 0},
    {"q": "What is the favorite kibble of a T-Rex?", "options": ["Basic Kibble", "Super Kibble", "Extraordinary Kibble", "Regular Kibble"], "answer": 2},
    {"q": "Which flying creature has the highest base HP?", "options": ["Argentavis", "Quetzal", "Wyvern", "Crystal Wyvern"], "answer": 3},
    {"q": "What is the base speed of a Giganotosaurus?", "options": ["25", "30", "35", "40"], "answer": 2},
    {"q": "Which creature is known as the 'Tank' of ARK?", "options": ["Bronto", "Titanosaur", "Paracer", "Managarmr"], "answer": 1},
    {"q": "What do you need to tame a Phoenix?", "options": ["Fire", "Heat", "Solar", "Ash"], "answer": 1},
    {"q": "Which sea creature has the highest oxygen stat?", "options": ["Megalodon", "Mosasaurus", "Basilosaurus", "Tusoteuthis"], "answer": 2},
    {"q": "What is the fastest land creature in ARK?", "options": ["Rex", "Argentavis", "Raptor", "Direwolf"], "answer": 2},
    {"q": "Which creature has the highest base health?", "options": ["T-Rex", "Bronto", "Titanosaur", "Giganotosaurus"], "answer": 2},
    {"q": "What is the best mount for carrying heavy loads?", "options": ["Argentavis", "Quetzal", "Mammoth", "Tusoteuthis"], "answer": 1},
    {"q": "Which creature is immune to radiation?", "options": ["Dilo", "Rex", "Aberrant Creatures", "Dodo"], "answer": 2},
    {"q": "What is the only creature that can harvest wood faster than a therizino?", "options": ["Beaver", "Mammoth", "Argentavis", "Chalicotherium"], "answer": 1},
    {"q": "Which creature can glide?", "options": ["Pteranodon", "Argentavis", "Chaarizard", "All flying"], "answer": 3},
    {"q": "What creature is required to ride a Yutyrannus?", "options": ["Nothing", "Flyer", "Ground mount", "Boss tame"], "answer": 2},
    {"q": "Which creature can only be tamed with a prism?", "options": ["Tusoteuthis", "Basilosaurus", "Mek", "Phoenix"], "answer": 2},
    {"q": "What is the base damage of a T-Rex?", "options": ["62", "48", "55", "70"], "answer": 0},
    {"q": "Which creature has the highest carry weight?", "options": ["Bronto", "Quetzal", "Titanosaur", "Managarmr"], "answer": 2},
    
    # ============ TAMING ============
    {"q": "What is the preferred food for taming a Trike?", "options": ["Meat", "Prime Meat", "Vegetables", "Kibble"], "answer": 2},
    {"q": "What is the kibble tier for taming a Pteranodon?", "options": ["Simple", "Basic", "Regular", "Super"], "answer": 1},
    {"q": "Which berry is best for taming herbivores?", "options": ["Mejoberry", "Narcoberry", "Stimberry", "Tintoberry"], "answer": 0},
    {"q": "What happens if you knockout a creature with too high taming effectiveness?", "options": ["It dies", "It wakes up", "It runs away", "Nothing"], "answer": 1},
    {"q": "What is the taming speed multiplier on official servers?", "options": ["1x", "2x", "0.5x", "10x"], "answer": 0},
    {"q": "Can you use a Giganotosaurus as a mount?", "options": ["Yes", "No", "Only with saddle", "Only on PvE"], "answer": 1},
    {"q": "What is required to mount a Tek Stego?", "options": ["Level 60", "Tek Saddle", "BPs unlocked", "Nothing"], "answer": 1},
    {"q": "Which creature requires Exceptional Kibble to tame?", "options": ["Rex", "Quetzal", "Griffin", "Rock Elemental"], "answer": 2},
    {"q": "How long does it take to tame a 150 Quetzal with kibble?", "options": ["1 hour", "2 hours", "4 hours", "8 hours"], "answer": 2},
    {"q": "What is the fastest way to knock out a dino?", "options": ["Punching", "Tranq arrows", "C4", "Metal"], "answer": 1},
    {"q": "What does Narcosis make creatures?", "options": ["Hungry", "Sleepy", "Angry", "Tame faster"], "answer": 1},
    {"q": "How much narcoberry puree for a 150 Argentavis?", "options": ["10", "25", "50", "100"], "answer": 2},
    {"q": "Can you tame a Giganotosaurus?", "options": ["Yes", "No", "Only Alpha", "Only with kibble"], "answer": 1},
    {"q": "What food do Rock Elementals eat?", "options": ["Meat", "Vegetables", "Stone", "Special"], "answer": 2},
    {"q": "What is needed to passive tame a Titanosaur?", "options": ["Kibble", "Nanny", "Vacuum Compartment", "Large trap"], "answer": 2},
    {"q": "How many narcotics for a 120 Brontosaurus?", "options": ["50", "100", "200", "400"], "answer": 2},
    {"q": "What is the favorite food of a Pteranodon?", "options": ["Raw Meat", "Raw Fish", "Kibble", "Berries"], "answer": 1},
    {"q": "Can you knock out a Griffin?", "options": ["Yes", "No", "Only with tranq", "Only on PvE"], "answer": 0},
    {"q": "What level do you need to ride a Argentavis?", "options": ["5", "15", "25", "35"], "answer": 2},
    {"q": "What is the taming bonus for using kibble?", "options": ["50%", "75%", "100%", "150%"], "answer": 1},
    
    # ============ BREEDING ============
    {"q": "What is the breeding interval for most large dinos?", "options": ["12-24 hours", "18-48 hours", "24-72 hours", "48-96 hours"], "answer": 1},
    {"q": "How long does it take for a Rex egg to mature (unboosted)?", "options": ["2 days", "3 days", "5 days", "7 days"], "answer": 3},
    {"q": "What determines baby dino stats?", "options": ["Parents only", "Baby level", "Imprinting", "Taming effectiveness"], "answer": 2},
    {"q": "What is the max imprint boost per stat?", "options": ["20%", "30%", "40%", "50%"], "answer": 2},
    {"q": "How does mutation work in ARK breeding?", "options": ["Random stats +2", "Random stats +5", "Color change only", "Nothing"], "answer": 0},
    {"q": "What is the baby mature speed multiplier on official servers?", "options": ["1x", "2x", "5x", "10x"], "answer": 0},
    {"q": "Can you breed two Giganotosaurus?", "options": ["Yes", "No", "Only same gender", "Only with mutation"], "answer": 1},
    {"q": "What food do baby dinos eat?", "options": ["Meat", "Vegetables", "Mature feed", "Kibble"], "answer": 2},
    {"q": "How do you get 100% imprint?", "options": ["Cuddle every 8 hours", "Cuddle once", "Auto imprint", "Buy it"], "answer": 0},
    {"q": "What happens if you breed a mutant with a normal?", "options": ["All mutate", "Some mutate", "No mutations", "Game crashes"], "answer": 1},
    {"q": "What is the mating cooldown after babies?", "options": ["12 hours", "24 hours", "48 hours", "72 hours"], "answer": 1},
    {"q": "How many mutations can stack on one stat?", "options": ["5", "10", "20", "Unlimited"], "answer": 2},
    {"q": "What is the mutation chance per egg?", "options": ["2.5%", "5%", "7.5%", "10%"], "answer": 2},
    {"q": "Can you breed in single player?", "options": ["Yes", "No", "Only with settings", "Only with mods"], "answer": 0},
    {"q": "What happens if you don't imprint a baby?", "options": ["It dies", "Lower stats", "Nothing", "Runs away"], "answer": 1},
    {"q": "How long does an egg stay fertile?", "options": ["1 hour", "2 hours", "4 hours", "Until hatched"], "answer": 3},
    {"q": "What is the best way to get high stats?", "Options": ["Breeding", "Taming", "Mutations", "All of the above"], "answer": 3},
    {"q": "Can you force twin eggs?", "options": ["Yes", "No", "Only with settings", "Only on official"], "answer": 1},
    {"q": "What stat doesn't pass to babies?", "options": ["Health", "Stamina", "Movement", "All pass"], "answer": 2},
    {"q": "How long is the mating season for Wyverns?", "options": ["24 hours", "48 hours", "72 hours", "1 week"], "answer": 1},
    
    # ============ MAPS & BIOMES ============
    {"q": "How many creatures are on The Island map?", "options": ["Around 60", "Around 80", "Around 100", "Around 120"], "answer": 1},
    {"q": "Which map is the first in ARK's storyline?", "options": ["Scorched Earth", "The Island", "Ragnarok", "Aberration"], "answer": 1},
    {"q": "What is the name of the desert region on The Island?", "options": ["The White Desert", "The Red Desert", "The Scorched Lands", "The Sand Desert"], "answer": 1},
    {"q": "Which map introduced the Desert biome?", "options": ["Ragnarok", "Scorched Earth", "Valguero", "The Island"], "answer": 1},
    {"q": "What element is found in the Underground of Aberration?", "options": ["Radiation", "Alpha Radiation", "Biohazard", "Toxic"], "answer": 1},
    {"q": "Which map has the most surface area?", "options": ["The Island", "Ragnarok", "Valguero", "Crystal Isles"], "answer": 2},
    {"q": "What is the name of the floating islands on Ragnarok?", "options": ["Highlands", "Floating Islands", "The Observatory", "Skys Cradle"], "answer": 1},
    {"q": "Which map is themed around Norse mythology?", "options": ["The Island", "Ragnarok", "Extinction", "Lost Island"], "answer": 1},
    {"q": "What is the name of the swamp region on The Island?", "options": ["Swamp", "Dead Isles", "The Bog", "Mire"], "answer": 0},
    {"q": "Which DLC introduced Lost Island?", "options": ["Genesis Part 1", "Genesis Part 2", "Lost Island", "Crystal Isles"], "answer": 2},
    {"q": "What is the only underwater map?", "options": ["The Island", "The Center", "Crystal Isles", "Abyss"], "answer": 1},
    {"q": "Which map has the most caves?", "options": ["The Island", "Ragnarok", "Aberration", "Valguero"], "answer": 2},
    {"q": "What is the hardest map in ARK?", "options": ["The Island", "Aberration", "Extinction", "Lost Island"], "answer": 1},
    {"q": "Which map is entirely underground?", "options": ["The Island", "Ragnarok", "Aberration", "Lost Island"], "answer": 2},
    {"q": "Which map has the city of Helios?", "options": ["Lost Island", "Extinction", "Genesis", "Crystal Isles"], "answer": 0},
    {"q": "How many main islands does Lost Island have?", "options": ["3", "5", "7", "9"], "answer": 1},
    
    # ============ GAME MECHANICS ============
    {"q": "What is the max level on official servers (without events)?", "options": ["105", "125", "150", "Unlimited"], "answer": 2},
    {"q": "How many engrams are there in base ARK?", "options": ["Around 100", "Around 150", "Around 200", "Around 250"], "answer": 2},
    {"q": "What is the max weight a player can have?", "options": ["200", "300", "500", "Unlimited with buffs"], "answer": 3},
    {"q": "How much food does a player need per minute?", "options": ["1", "2", "5", "10"], "answer": 0},
    {"q": "What is the crafting speed multiplier for a Smithy?", "options": ["1x", "2x", "3x", "5x"], "answer": 1},
    {"q": "How many crop plots can a single generator power?", "options": ["1", "2", "5", "Unlimited"], "answer": 2},
    {"q": "What is the purpose of a Behemoth Gateway?", "options": ["Vehicle access", "Dino access", "Player only", "Teleport"], "answer": 0},
    {"q": "Which structure can only be placed on foundation?", "options": ["Forge", "Chemistry Bench", "Tek Generator", "All of them"], "answer": 3},
    {"q": "What is the max turret range?", "options": ["30 meters", "50 meters", "70 meters", "100 meters"], "answer": 2},
    {"q": "How much HP does a metal wall have?", "options": ["500", "1000", "2000", "5000"], "answer": 2},
    {"q": "What is the player respawn timer?", "options": ["10 seconds", "30 seconds", "1 minute", "5 minutes"], "answer": 1},
    {"q": "How much damage does a stone pickaxe do?", "options": ["17", "25", "35", "50"], "answer": 1},
    {"q": "What is the fastest way to gain XP?", "options": ["Killing dinos", "Boss fights", "Events", "Crafting"], "answer": 2},
    {"q": "How many engram points per level?", "options": ["3", "5", "7", "10"], "answer": 0},
    {"q": "What does the fortitude stat protect against?", "options": ["Physical", "Radiation", "Cold", "All"], "answer": 1},
    {"q": "How long does sparkpowder last in a forge?", "options": ["30 seconds", "1 minute", "2 minutes", "5 minutes"], "answer": 2},
    {"q": "What is the max turret damage?", "options": ["35", "50", "75", "100"], "answer": 1},
    {"q": "How many turrets to power a Tek cliff platform?", "options": ["0", "4", "8", "12"], "answer": 0},
    {"q": "What is the bed respawn radius?", "options": ["100", "500", "1000", "Unlimited"], "answer": 2},
    {"q": "How much health does a player have at level 100 (no ascension)?", "options": ["1500", "2000", "2500", "3000"], "answer": 1},
    
    # ============ ITEMS & RESOURCES ============
    {"q": "What is the stack size of Raw Meat?", "options": ["20", "50", "100", "200"], "answer": 1},
    {"q": "How many hits does a metal pillar take to destroy?", "options": ["50", "100", "200", "500"], "answer": 2},
    {"q": "What is the best fertilizer for crops?", "options": ["Hide", "Rotten Meat", "Fertilizer", "Oil"], "answer": 2},
    {"q": "What do you need to craft Tek Armor?", "options": ["Metal", "Element", "Polymer", "Obsidian"], "answer": 1},
    {"q": "How much metal does a metal wall cost?", "options": ["10", "25", "50", "100"], "answer": 2},
    {"q": "What is the weight of a complete set of ASCendant Armor?", "options": ["20", "50", "100", "200"], "answer": 1},
    {"q": "Which resource is used in Tek generators?", "options": ["Gas", "Fuel", "Element", "Oil"], "answer": 2},
    {"q": "What is the max stack for Metal Ingots?", "options": ["50", "100", "200", "500"], "answer": 1},
    {"q": "What do you craft in a Refining Forge?", "options": ["Metal", "Ingots", "Alloys", "Polymers"], "answer": 1},
    {"q": "How many arrow types are in ARK?", "options": ["2", "3", "4", "5"], "answer": 2},
    {"q": "What is polymer used for?", "options": ["Weapons", "Tools", "Tek items", "All of the above"], "answer": 3},
    {"q": "How much element for full Tek armor?", "options": ["100", "200", "300", "500"], "answer": 2},
    {"q": "What is obsidian used for?", "options": ["Weapons", "Tools", "Crafting", "All of the above"], "answer": 3},
    {"q": "How many cannonballs for a metal gate?", "options": ["1", "2", "3", "4"], "answer": 2},
    {"q": "What is the best armor in the game?", "options": ["Metal", "Tek", "ASCendant", "Mastercraft"], "answer": 2},
    {"q": "How much durability does a mastercraft crossbow have?", "options": ["500", "750", "1000", "1500"], "answer": 2},
    {"q": "What does a compass point to?", "options": ["North", "Your bed", "Nearest tribe", "Nothing"], "answer": 0},
    {"q": "How many charges in a full battery?", "options": ["50", "100", "200", "500"], "answer": 2},
    {"q": "What is the weight of a rocket launcher?", "options": ["20", "30", "50", "100"], "answer": 2},
    {"q": "How many engrams require element?", "options": ["1", "3", "5", "10"], "answer": 2},
    
    # ============ ENGRAMS ============
    {"q": "What level do you unlock the Longneck Rifle?", "options": ["35", "45", "55", "65"], "answer": 2},
    {"q": "What level do you unlock the Compound Bow?", "options": ["30", "40", "50", "60"], "answer": 2},
    {"q": "How many engram points to unlock everything (no boosters)?", "options": ["Around 5000", "Around 7500", "Around 10000", "Around 15000"], "answer": 1},
    {"q": "What engram replaces the Spyglass at level 45?", "options": ["GPS", "Beacon", "Tracker", "Map"], "answer": 1},
    {"q": "What is the first crafting structure you unlock?", "options": ["Smithy", "Anvil", "Fabricator", "Chem Bench"], "answer": 0},
    {"q": "At what level do you unlock Metal Armor?", "options": ["25", "35", "45", "55"], "answer": 2},
    {"q": "What is required to learn Tek Saddles?", "options": ["Level", "Boss trophies", "Blueprints", "Quest"], "answer": 1},
    {"q": "How many engrams does the Scorched Earth DLC add?", "options": ["Around 20", "Around 40", "Around 60", "Around 80"], "answer": 1},
    {"q": "What is the engram for the Argentavis saddle?", "options": ["Level 35", "Level 45", "Level 55", "Level 65"], "answer": 1},
    {"q": "Can you unlock engrams on a dedicated server without points?", "options": ["Yes", "No", "Only PvE", "Only PvP"], "answer": 0},
    {"q": "What level do you unlock the Longneck?", "options": ["35", "45", "55", "65"], "answer": 2},
    {"q": "When do you unlock the Fabricator?", "options": ["Level 35", "Level 45", "Level 55", "Level 65"], "answer": 2},
    {"q": "What level gives you the chemistry bench?", "options": ["35", "45", "55", "65"], "answer": 2},
    {"q": "How many tek engrams are there?", "options": ["Around 10", "Around 20", "Around 30", "Around 50"], "answer": 2},
    {"q": "What is the first weapon engram?", "options": ["Pickaxe", "Bow", "Spear", "Club"], "answer": 1},
    {"q": "What level unlocks the smithy?", "options": ["5", "10", "15", "20"], "answer": 1},
    {"q": "When do you learn the tranq arrow?", "options": ["Level 15", "Level 25", "Level 35", "Level 45"], "answer": 1},
    {"q": "What is the last engram in the game?", "options": ["Tek Saddle", "Mek Saddle", "Deathworm", "Boss"], "answer": 1},
    {"q": "How many engrams are in Scorched Earth?", "options": ["20", "40", "60", "80"], "answer": 1},
    {"q": "What level unlocks riot armor?", "options": ["55", "65", "75", "85"], "answer": 2},
    
    # ============ BOSSES ============
    {"q": "How many boss engrams can you unlock from the Island?", "options": ["1", "2", "3", "4"], "answer": 2},
    {"q": "What is the health multiplier for the Manticore on hard?", "options": ["2x", "3x", "5x", "10x"], "answer": 2},
    {"q": "What element does the Island boss drop?", "options": ["Blue", "Red", "Green", "Purple"], "answer": 0},
    {"q": "How many artifacts are on The Island?", "options": ["3", "5", "7", "9"], "answer": 2},
    {"q": "Which boss is the easiest?", "options": ["Dragon", "Manticore", "Broodmother", "Megapithecus"], "answer": 1},
    {"q": "What do you need to summon the Island bosses?", "options": ["Portals", "Artifacts", "Beacons", "Eggs"], "answer": 1},
    {"q": "How many Tek Tier engrams do you get from defeating all bosses?", "options": ["3", "5", "7", "All"], "answer": 2},
    {"q": "What is the reward for defeating the Dragon?", "options": ["Element", "Tek Grenade", "Ascendant Gear", "All of the above"], "answer": 3},
    {"q": "Can you fight all bosses in one run?", "options": ["Yes", "No", "Only on Extinction", "Lost Island"], "answer": 1},
    {"q": "Can you summon bosses without artifacts?", "options": ["Yes", "No", "Only on Extinction", "Lost Island"], "answer": 1},
    {"q": "What is the Rockwell boss in?", "options": ["Aberration", "Extinction", "Lost Island", "Crystal Isles"], "answer": 0},
    {"q": "How many boss trophies needed for all Tek?", "options": ["3", "5", "7", "9"], "answer": 2},
    {"q": "What does the Broodmother drop?", "options": ["Blue element", "Red element", "Green element", "Purple element"], "answer": 1},
    {"q": "Can you fight bosses on foot?", "options": ["Yes", "No", "Only with flyer", "Only with dino"], "answer": 0},
    {"q": "What is the hardest boss in ARK?", "options": ["Dragon", "Manticore", "King Titan", "All equal"], "answer": 2},
    {"q": "How many element does the easiest boss drop?", "options": ["50", "100", "150", "200"], "answer": 0},
    
    # ============ LOST COLONY ============
    {"q": "What is the main theme of the Lost Colony?", "options": ["Post-apocalyptic", "Futuristic", "Ancient ruins", "Underwater"], "answer": 0},
    {"q": "What creatures are native to Lost Colony?", "options": ["Dinos", "Robots/Aliens", "Both", "Neither"], "answer": 1},
    {"q": "What is the unique resource in Lost Colony?", "options": ["Element", "Blueprinted supplies", "Alien tech", "All of the above"], "answer": 3},
    {"q": "How many biomes does Lost Colony have?", "options": ["3", "5", "7", "9"], "answer": 2},
    {"q": "What is the main city called in Lost Colony?", "options": ["Orion", "Helios", "Haven", "Sanctuary"], "answer": 1},
    {"q": "Are there wild dinos in Lost Colony?", "options": ["Yes", "No", "Only in sim", "Only on edges"], "answer": 1},
    {"q": "What is the weather like in Lost Colony?", "options": ["Clear", "Stormy", "Variable", "No weather"], "answer": 2},
    {"q": "Can you tame native creatures in Lost Colony?", "options": ["Yes", "No", "Only some", "Only with kibble"], "answer": 0},
    {"q": "What is the difficulty level of Lost Colony?", "options": ["1", "3", "5", "Infinite"], "answer": 3},
    
    # ============ GENERAL LORE ============
    {"q": "Who created ARK: Survival Evolved?", "options": ["Bungie", "Studio Wildcard", "Epic Games", "Valve"], "answer": 1},
    {"q": "When was ARK officially released?", "options": ["2015", "2016", "2017", "2018"], "answer": 2},
    {"q": "What engine does ARK use?", "options": ["Unity", "Unreal 4", "Source 2", "CryEngine"], "answer": 1},
    {"q": "How much did ARK sell on early access?", "options": ["1 million", "3 million", "5 million", "10 million"], "answer": 2},
    {"q": "What is the ARK's official nickname?", "options": ["The Island", "The Sandbox", "Dino Evolved", "Survivors Paradise"], "answer": 1},
    {"q": "How many official ARK Expansion maps are there?", "options": ["3", "5", "7", "9"], "answer": 2},
    {"q": "What is the base game map called?", "options": ["The Island", "Origin", "ARK Prime", "The Beginning"], "answer": 0},
    {"q": "What year did ARK mobile release?", "options": ["2016", "2017", "2018", "2019"], "answer": 0},
    {"q": "Is ARK available on Nintendo Switch?", "options": ["Yes", "No", "Only mobile", "Only cloud"], "answer": 0},
    {"q": "How long was ARK in early access?", "options": ["6 months", "1 year", "2 years", "3 years"], "answer": 2},
    {"q": "What year was Lost Island released?", "options": ["2020", "2021", "2022", "2023"], "answer": 2},
    {"q": "How many ARK games are there?", "options": ["2", "3", "4", "5"], "answer": 2},
    {"q": "What platform did ARK launch on first?", "options": ["PC", "Xbox", "PS4", "Mobile"], "answer": 0},
    {"q": "What was ARK's original name?", "options": ["Project ARK", "Dino Survival", "Primordial", "Prehistoric"], "answer": 1},
    {"q": "Is ARK: Survival Of The Fittest canon?", "options": ["Yes", "No", "Spin-off", "PVP only"], "answer": 0},
    {"q": "What company owns Studio Wildcard?", "options": ["Microsoft", "Sony", "Embracer Group", "Tencent"], "answer": 2},
    {"q": "How many total creatures in all ARK maps?", "options": ["100+", "150+", "200+", "250+"], "answer": 2},
    {"q": "What is the name of the space map?", "options": ["Lost Island", "Space", "Extinction", "Orbit"], "answer": 0},
    {"q": "Which ARK has the most DLC?", "options": ["The Island", "Scorched Earth", "Lost Island", "All equal"], "answer": 0},
    {"q": "Is ARK 2 coming?", "options": ["Yes", "No", "Already out", "Canceled"], "answer": 0},
    
    # ============ SURVIVAL MECHANICS ============
    {"q": "How much health does a player have at level 1?", "options": ["100", "150", "200", "250"], "answer": 1},
    {"q": "How many status effects can a player have?", "options": ["1", "3", "5", "Unlimited"], "answer": 3},
    {"q": "What does the Food stat affect?", "options": ["Hunger", "Stamina", "Oxygen", "Temperature"], "answer": 0},
    {"q": "How long does it take to starve (full food to 0)?", "options": ["5 minutes", "10 minutes", "15 minutes", "20 minutes"], "answer": 2},
    {"q": "What is the max stamina for a player?", "options": ["100", "150", "200", "250"], "answer": 1},
    {"q": "How does encumbrance affect movement?", "options": ["Slower", "Faster", "No effect", "Can sprint"], "answer": 0},
    {"q": "What happens at 0 health?", "options": ["Respawn", "Knockout", "Death", "Revive"], "answer": 2},
    {"q": "How many respecs do you get in ARK?", "options": ["0", "1", "3", "Unlimited"], "answer": 0},
    {"q": "What is the crafting speed bonus from the Mastercrafting perk?", "options": ["10%", "15%", "20%", "25%"], "answer": 2},
    {"q": "How much damage reduction does the fortitude stat give?", "options": ["1 per point", "2 per point", "0.5 per point", "None"], "answer": 0},
    {"q": "What is the max level without ascending?", "options": ["105", "115", "125", "150"], "answer": 2},
    {"q": "How much water does a player lose per minute?", "options": ["1", "2", "3", "5"], "answer": 1},
    {"q": "What does cold do to players?", "options": ["Nothing", "Health drain", "Stamina drain", "Speed boost"], "answer": 1},
    {"q": "What does heat do to players?", "options": ["Nothing", "Health drain", "Water drain", "Speed boost"], "answer": 2},
    {"q": "How much health does a player heal per second?", "options": ["1", "2", "5", "10"], "answer": 0},
    {"q": "What is the oxygen stat used for?", "options": ["Swimming", "Flying", "Running", "All"], "answer": 0},
    {"q": "How long can you hold your breath?", "options": ["10 seconds", "20 seconds", "30 seconds", "60 seconds"], "answer": 2},
    {"q": "What is the starting inventory size?", "options": ["12", "16", "20", "24"], "answer": 1},
    {"q": "How does snow affect players?", "options": ["Nothing", "Cold", "Slow", "Heal"], "answer": 1},
    {"q": "What is the torpor stat for?", "options": ["Nothing", "Knockout", "Speed", "Health"], "answer": 1},
    
    # ============ TEK TIER ============
    {"q": "What is needed to power Tek structures?", "options": ["Electricity", "Element", "Gas", "Fuel"], "answer": 1},
    {"q": "What color is Tek Armor?", "options": ["Blue", "Purple", "Green", "Black"], "answer": 0},
    {"q": "What can the Tek Replicator craft?", "options": ["Everything", "Tek only", "Ascendant only", "Mastercraft only"], "answer": 1},
    {"q": "How much element does a full charge give?", "options": ["50", "100", "200", "500"], "answer": 2},
    {"q": "What is the Tek Saddle requirement?", "options": ["Level 60", "Level 70", "Level 80", "Level 90"], "answer": 1},
    {"q": "Can Tek structures be damaged by metal tools?", "options": ["Yes", "No", "Only with charges", "Only by explosions"], "answer": 1},
    {"q": "What is the unique feature of Tek Helmet?", "options": ["Night vision", "Air supply", "Energy shield", "All of the above"], "answer": 3},
    {"q": "How many Tek tiers are there?", "options": ["3", "5", "7", "10"], "answer": 1},
    {"q": "What is required to unlock Tek Tier?", "options": ["All boss trophies", "Level 100", "All blueprints", "50 element"], "answer": 0},
    {"q": "Does Tek work offline?", "options": ["Yes", "No", "Only with battery", "Only with generator"], "answer": 1},
    {"q": "What is the Tek Teleporter range?", "options": ["500m", "1km", "5km", "Unlimited"], "answer": 2},
    {"q": "Can you use Tek on Lost Island?", "options": ["Yes", "No", "Only in biomes", "Only with element"], "answer": 0},
    {"q": "What does the Tek Grenade do?", "options": ["Damage", "Stun", "Teleport", "Destroy tek"], "answer": 1},
    {"q": "How much health does a Tek Wall have?", "options": ["2000", "3000", "5000", "10000"], "answer": 2},
    {"q": "What is the best Tek mount?", "options": ["Tek Rex", "Tek Quetzal", "Tek Stego", "All equal"], "answer": 3},
    {"q": "Does Tek need fuel?", "options": ["Yes", "No", "Only generator", "Only lights"], "answer": 0},
    {"q": "What can the Tek Camera do?", "options": ["Photo", "Video", "Scan", "All"], "answer": 3},
    {"q": "How many charges for a full Tek Battery?", "options": ["100", "200", "300", "500"], "answer": 1},
    {"q": "Can you hide in a Tek Sleeping Pod?", "options": ["Yes", "No", "Only offline", "Only with tribe"], "answer": 0},
    {"q": "What is the Tek Bird's special?", "options": ["Laser", "Rocket", "Shield", "All"], "answer": 3},
    
    # ============ SADDLES ============
    {"q": "What level is the Pteranodon saddle?", "options": ["25", "35", "45", "55"], "answer": 1},
    {"q": "What level is the T-Rex saddle?", "options": ["55", "65", "75", "85"], "answer": 2},
    {"q": "What is the highest level saddle?", "options": ["85", "95", "100", "110"], "answer": 1},
    {"q": "Do all creatures need saddles?", "options": ["Yes", "No", "Only above level 30", "Only combat dinos"], "answer": 1},
    {"q": "What is the Bronto saddle level?", "options": ["45", "55", "65", "75"], "answer": 2},
    {"q": "Can you craft tribal saddles?", "options": ["Yes", "No", "Only found", "Only bought"], "answer": 1},
    {"q": "What is the Quetzal saddle level?", "options": ["65", "75", "85", "95"], "answer": 1},
    {"q": "How many unique saddle types are there?", "options": ["Around 30", "Around 50", "Around 70", "Around 100"], "answer": 2},
    {"q": "What is the Giganotosaurus saddle called?", "options": ["Basic", "Elemental", "Tek", "None (can't ride)"], "answer": 3},
    {"q": "What level is the Argentavis saddle?", "options": ["25", "35", "45", "55"], "answer": 1},
    {"q": "What level is the Mammoth saddle?", "options": ["35", "45", "55", "65"], "answer": 2},
    {"q": "Can you ride a Wyvern without a saddle?", "options": ["Yes", "No", "Only with kibble", "Only after level"], "answer": 0},
    {"q": "What level is the Stegosaurus saddle?", "options": ["25", "35", "45", "55"], "answer": 1},
    {"q": "Do you need a saddle for a Thylacoleo?", "options": ["Yes", "No", "Only at level", "Only with BP"], "answer": 0},
    {"q": "What is the highest level tek saddle?", "options": ["85", "95", "100", "110"], "answer": 1},
    {"q": "Can you put armor on a Quetzal?", "options": ["Yes", "No", "Only platform", "Only with saddle"], "answer": 0},
    {"q": "What level is the Trike saddle?", "options": ["15", "25", "35", "45"], "answer": 1},
    {"q": "Do you need a saddle to fly?", "options": ["Yes", "No", "Only with platform", "Only above 30"], "answer": 0},
    {"q": "What level is the Raptor saddle?", "options": ["15", "25", "35", "45"], "answer": 1},
    {"q": "Can you ride a Rock Elemental?", "options": ["Yes", "No", "Only withtek", "Only in boss"], "answer": 0},
]

def get_static_question():
    """Get a random trivia question."""
    import random
    return random.choice(ARK_TRIVIA_QUESTIONS)

def get_question_count():
    """Get total number of questions."""
    return len(ARK_TRIVIA_QUESTIONS)
